confluentinc/kafka-images

Jenkinsfile, README.md, ce-kafka/Dockerfile.ubi8, kafka-connect-base/Dockerfile.ubi8, kafka-connect/Dockerfile.ubi8, kafka/Dockerfile.ubi8, server-connect-base/Dockerfile.ubi8, server-connect/Dockerfile.ubi8, server/Dockerfile.ubi8, zookeeper/Dockerfile.ubi8
The product team wants to change the tags on the rhel images to ubi8.
=> ST-2560: Rename rhel image ubi8

server-connect-base/include/etc/confluent/docker/configure
Opening a new PR for issue #37 based on 5.4.x
=> cp-server-connect - Make internal converter env vars optional #37

server-connect/Dockerfile.ubi8, server/Dockerfile.ubi8, zookeeper/Dockerfile.ubi8
* Add description label to CP Server Connect Dockerfile
* Add description label to Zookeeper image
* Add description label to CP Server Dockerfile
=> Add description label to Dockerfiles (#96)

ce-kafka/Dockerfile.deb8, ce-kafka/Dockerfile.ubi8, kafka-connect-base/Dockerfile.deb8, kafka-connect-base/Dockerfile.ubi8, kafka/Dockerfile.deb8, kafka/Dockerfile.ubi8, server-connect-base/Dockerfile.deb8, server-connect-base/Dockerfile.ubi8, server/Dockerfile.deb8, server/Dockerfile.ubi8, zookeeper/Dockerfile.deb8, zookeeper/Dockerfile.ubi8
Disables world write access on directories.
=> feat: Disable world write access on directories

kafka-connect-base/Dockerfile.ubi8, kafka/Dockerfile.ubi8, server-connect-base/Dockerfile.ubi8
Fixes https://github.com/confluentinc/kafka-images/issues/127
As a follow-on to https://github.com/confluentinc/kafka-images/pull/116
=> fix: Ensure owner is appuser:appuser in /etc/kafka

ce-kafka/pom.xml, kafka-connect-base/pom.xml, kafka-connect/pom.xml, kafka/pom.xml, pom.xml, server-connect-base/pom.xml, server-connect/pom.xml, server/pom.xml, zookeeper/pom.xml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 5.5.14-post to 5.5.x)

ce-kafka/README.md, kafka-connect-base/README.md, kafka-connect/README.md, kafka/README.md, server-connect-base/README.md, server-connect/README.md, server/README.md, zookeeper/README.md
@gracechensd same commit as before but we need in `-post` branches instead of just `-.x`
=> update license section in READMEs

local/pom.xml
=> Updating org.json to 20230227

local/pom.xml
=> Updating org.json to 20230227 (7.4.x)

local/pom.xml
=> Updating org.json to 20230227 (7.5.x)

local/pom.xml
*What*
Updated org.json to 20231013.
=> KSECURITY-2029: Updated org.json to 20231013

service.yml
https://confluentinc.atlassian.net/browse/KCP-50?focusedCommentId=2577552
=> Enable image signing

service.yml
This is an autogenerated pull request by `pint` due to a merge conflict failure seen during [`pint merge`](http://go/pint-merge-service).
1. Resolve all conflicts (either via web editor or the command line)
2. Commit merge
3. Obtain approvals from reviewers
4. **(IMPORTANT)** After obtaining approvals, click the dropdown menu on the merge button and select **"Create a merge commit"** 
5. Click the "Merge pull request" button
6. Re-run [`pint merge`]( http://go/pint-merge-service)
NOTE: **"Create a merge commit"** option must be used to ensure all commits from the head branch is added to the base branch.
Please reach out to the Developer Productivity team on Slack at #devprod-eng or #devprod-oncall
=> Merge Conflict Resolution (from 6.2.x to 7.0.x)

.semaphore/cp_dockerfile_build.yml, .semaphore/cp_dockerfile_promote.yml, .semaphore/project.yml, .semaphore/semaphore.yml, ce-kafka/Dockerfile.ubi8, kafka-connect-base/Dockerfile.ubi8, kafka-connect/Dockerfile.ubi8, server-connect-base/Dockerfile.ubi8, server-connect/Dockerfile.ubi8, sonar-project.properties
Triggered run-service-bot and generated the .semaphore files.
Use the newly built image in `DOCKER_REGISTRY` instead of `DOCKER_UPSTREAM_REGISTRY`.
=> Chore service bot update

.semaphore/cp_dockerfile_build.yml, .semaphore/project.yml, .semaphore/semaphore.yml
Rerun service bot to generate the .semaphore files with service.yml with tasks configs.
=> Add tasks configs

.github/CODEOWNERS, .semaphore/cp_dockerfile_build.yml, .semaphore/cp_dockerfile_promote.yml, .semaphore/semaphore.yml
=> Chore service bot 2

.semaphore/cp_dockerfile_build.yml
=> chore: update repo semaphore task

.semaphore/cp_dockerfile_build.yml, .semaphore/semaphore.yml
=> Update packaging bucket names

.semaphore/semaphore.yml
Moving out of cc-root-1 aws account , updating s3 bucket reference
jenkins-confluent-packages -> dev-confluent-packages-654654529379-us-west-2
=> Update s3 bucket name

.semaphore/cp_dockerfile_build.yml, .semaphore/cp_dockerfile_promote.yml, .semaphore/semaphore.yml, sonar-project.properties
These changes are brought in by servicebot
The changes include:
- fix docker tag for latest on dockerhub, the if clause has been fixed
- removal of checks for beta releases
- support for versioned branches (7.0.16)
- skip dependency checks
=> Servicebot changes

zookeeper/include/etc/confluent/docker/zookeeper.properties.template
Add tcpKeepAlive to be specified as an argument to the docker image
=> add tcpKeepAlive to ZK properties template

README.md, kafka-connect-base/Dockerfile.ubi9, kafka-connect/Dockerfile.ubi9, kafka/Dockerfile.ubi9, local/Dockerfile.ubi9, server-connect-base/Dockerfile.ubi9, server-connect/Dockerfile.ubi9, server/Dockerfile.ubi9, service.yml
[cp-base-new](https://confluentinc.atlassian.net/browse/CP-base-new) is upgraded to ubi9-minimal in https://github.com/confluentinc/common-docker/pull/668
CP images are being upgraded to ubi9
Semaphore pipeline changes will be brought in using servicebot (eg. https://github.com/confluentinc/common-docker/pull/693)
=> CPBR-2365: Upgrade component images to ubi9-minimal

Jenkinsfile.disable, kafka-connect-base/include/etc/confluent/docker/log4j.properties.template, kafka/Dockerfile.ubi9, kafka/include/etc/confluent/docker/configure, kafka/include/etc/confluent/docker/ensure, kafka/include/etc/confluent/docker/kafka.properties.template, local/Dockerfile.ubi9, local/include/etc/confluent/docker/configure, local/include/etc/confluent/docker/kafka-propertiesSpec.json, server-connect-base/include/etc/confluent/docker/log4j.properties.template, server/Dockerfile.ubi9, server/include/etc/confluent/docker/configure, server/include/etc/confluent/docker/ensure, server/include/etc/confluent/docker/kafka.properties.template, service.yml
Remove ZK references from kafka-images
In this pass, I am just fixing up the necessary code to build the images.
- Tests will be fixed in a later PR
- Examples will be updated by https://github.com/confluentinc/kafka-images/pull/380
=> KMETA 2181 - Remove ZK references from kafka-images

.semaphore/cp_dockerfile_build.yml, .semaphore/cp_dockerfile_promote.yml, .semaphore/semaphore.yml, service.yml
- applied service bot template changes https://github.com/confluentinc/cc-service-bot/pull/1477 to update docker build and docker promote workflows
- added SKIP_COMMUNITY flag/ task param to skip building and publishing community docker images
=> CPBR-2445 Apply service bot changes

server-connect-base/Dockerfile.ubi9, server-connect-base/include/etc/confluent/docker/configure, server-connect-base/include/etc/confluent/docker/ensure, server-connect-base/include/etc/confluent/docker/kafka-connect.properties.template, server-connect-base/include/etc/confluent/docker/log4j2.yaml.template
This PR will have following changes:
- Package dedupe script execution
- Changed yum to microdnf
- cub/dub changed to ub
----
Nightly image size: 3900 MB
Refreshed image size: 2535 MB
---
For more detail and testing strategy: https://confluentinc.atlassian.net/browse/CPBR-2166
=> CPBR-2166 | Docker refresh for cp-server-connect image reduction
