kafka/include/etc/confluent/docker/ensure
kafka/include/etc/confluent/docker/kafka.properties.template
server/include/etc/confluent/docker/ensure
server/include/etc/confluent/docker/kafka.properties.template
zookeeper/include/etc/confluent/docker/zookeeper.properties.template

In order to support New TLS support in ZK, we need:
1) Add many properties to the ZK template for docker environment variables related mostly to SSL configs
2) modify kafka and server properties for one specific property (zookeeper.clientCnxnSocket) which doesn't follow the normal pattern for converting ENV variables
3) modify kafka and server ensure to skip ZK_READY check for SSL as the connectivity check doesn't support TLS. This can be removed once that support is added in the future.

[ST-3300] modify properties and ensure files for ZK TLS support

---

kafka-connect-base/include/etc/confluent/docker/run
kafka/include/etc/confluent/docker/run
server-connect-base/include/etc/confluent/docker/run
server/include/etc/confluent/docker/run
zookeeper/include/etc/confluent/docker/run

We don't want to print the environment variables in the logs during startup because they contain sensitive data.

ST-3599: Remove show_env function because it exposes secrets

---

kafka-connect/Dockerfile.deb8
kafka-connect/Dockerfile.ubi8
server-connect/Dockerfile.deb8
server-connect/Dockerfile.ubi8

Fixing these build failures now that the connector OS packages are no longer being built: https://jenkins.confluent.io/job/confluentinc/job/kafka-images/job/master/137/console

Stop installing connectors through OS Packages

---

kafka-connect-base/Dockerfile.ubi8
server-connect-base/Dockerfile.ubi8

Currently with UBI images, we don't have /usr/share/confluent-hub-components created by default and appuser doesn't have permissions to create the directory, so confluent hub installs will fail (without providing an existing target directory).

[ST-3964] create /usr/share/confluent-hub-components directory in UBI images

---

kafka-connect-base/Dockerfile.ubi8
server-connect-base/Dockerfile.ubi8

When connectors are installed from confluent hub, they update the plugin path for worker configs.  This involves updating kafka files and schema-registry.  However with UBI images for connect, the user doesn't have write access to /etc/schema-registry.

modify SR permissions for connect-hub installs

---

server/include/etc/confluent/docker/kafka.properties.template

The extra `-%}` is copied as a literal in the final kafka.properties file. That results in a config named `-%}` being created. This config is problematic for REST Proxy, because REST Proxy assumes all config names are URL safe, therefore it tries to construct an URL with this config name on it and it fails.

Remove extra -%} in kafka.properties.

---

ce-kafka/Dockerfile.ubi8
kafka-connect-base/Dockerfile.ubi8
kafka-connect/Dockerfile.ubi8
kafka/Dockerfile.ubi8
server-connect-base/Dockerfile.ubi8
server-connect/Dockerfile.ubi8
server/Dockerfile.ubi8
zookeeper/Dockerfile.ubi8

From https://github.com/confluentinc/common-docker/pull/100
We shouldn't be calling `yum update` as other non-pinned dependencies (like zulu11 JDK) can be unknowingly updated.
For 6.0.x we are also building EL8 Clients, so we can now utilize yum var's `$releasever` to point to the EL8's package's endpoint, rather than the work around we were doing for 5.4.x/5.5.x and using EL7's endpoint.

MINOR: Don't yum update & use $releasever in yum config

---

ce-kafka/Dockerfile.ubi8
kafka-connect-base/Dockerfile.ubi8
kafka-connect/Dockerfile.ubi8
kafka/Dockerfile.ubi8
server-connect-base/Dockerfile.ubi8
server-connect/Dockerfile.ubi8
server/Dockerfile.ubi8
zookeeper/Dockerfile.ubi8

"Backporting" https://github.com/confluentinc/kafka-images/pull/51
* Don't run `yum update` - thats done in the base image: https://github.com/confluentinc/common-docker/pull/101
* Didn't backport the `$releasever` change, as we're not generating EL8 Clients for 5.4/5.5 - These CP versions will use the EL7 RPMs. Redhat is generally backards ABI compatible.

ST-4157: Don't yum update

---

kafka/Dockerfile.ubi8

with UBI images, the appuser doens't have permissions directly to /var/log and this causes startup issues in 2.6/6.0, so fixing (this is the same as the permissions in the server image already).
Verified with cp-all-in-one-community with a local build.

[ST-4294] update folder ownership for UBI8 images

---

Jenkinsfile
ce-kafka/pom.xml
kafka-connect-base/pom.xml
kafka-connect/pom.xml
kafka/pom.xml
pom.xml
server-connect-base/pom.xml
server-connect/pom.xml
server/pom.xml
zookeeper/pom.xml

Setting the jenkins config to use nano versioning. Removed all of the snapshot versions and replaced with nano versions. Updated all of the dependency versions.
These changes will be merged during phase two of the nano versioning roll out.

ST-3461: Implement nano versioning

---

kafka-connect-base/Dockerfile.ubi8

Why
kafka-connect-image missing `CONNECT_PLUGIN_PATH ` while server-connect-base still have that path. It might get removed mistakenly during deb to ubi transfer. https://github.com/confluentinc/kafka-images/pull/9/files#diff-b0c4beb1277b361ec5ab6f6c4fc6760fb10f1f82f03aaa56d5fdff2d0a8921b8L65
How
Add the missing path back to the kafka-connect-base image, that change will be merged up to master branch.

Add missing path back

---

README.md
ce-kafka/README.md
kafka-connect-base/README.md
kafka-connect/README.md
kafka/README.md
server-connect-base/README.md
server-connect/README.md
server/README.md
zookeeper/README.md

This is the first step in fixing all of the README files. I've picked one and want to make sure the process is valid for updating them before proceeding with the others. 
/cc @elismaga please can you review, and let me know if this is an appropriate way to do it. I've committed the existing README in Markdown form for https://hub.docker.com/r/confluentinc/cp-kafka-connect and then subsequent edits to it. 
I noticed on DockerHub that it says that READMEs can be set automatically on build - is this something that our tooling would support?

Fix READMEs (DOCS-6716)

---

server-connect/Dockerfile.ubi8
server/Dockerfile.ubi8
zookeeper/Dockerfile.ubi8

Some image scanning tools that check for vulnerabilities and OCI image best
practices expect to find a `description` label on images that is not inherited
from base images. The proposed change addresses this requirement for
ZooKeeper, CP Server, and CP Connect Server.

Add description label to Dockerfiles

---

ce-kafka/Dockerfile.deb8
ce-kafka/Dockerfile.ubi8
kafka-connect-base/Dockerfile.deb8
kafka-connect-base/Dockerfile.ubi8
kafka-connect/Dockerfile.deb8
kafka-connect/Dockerfile.ubi8
kafka/Dockerfile.deb8
kafka/Dockerfile.ubi8
server-connect-base/Dockerfile.deb8
server-connect-base/Dockerfile.ubi8
server-connect/Dockerfile.deb8
server-connect/Dockerfile.ubi8
server/Dockerfile.deb8
server/Dockerfile.ubi8
zookeeper/Dockerfile.deb8
zookeeper/Dockerfile.ubi8

Couple of changes:
* Remove confluent's repo config. Confluent's images don't need to be able to update to the next CP release (Customers should be consuming the next versioned docker release)
* Removed the AllowUnauthenticated piece: In practice, we always import the public key for GPG automation validation.

build: Remove confluent yum/apt repo after installation

---

zookeeper/Dockerfile.ubi8

After #116 was merged in, the UBI images failed to start:
```
% docker run -e ZOOKEEPER_CLIENT_PORT=32181 -e ZOOKEEPER_TICK_TIME=2000 368821881613.dkr.ecr.us-west-2.amazonaws.com/confluentinc/cp-zookeeper:5.4.x-latest-ubi8
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Configuring ...
Command [/usr/local/bin/dub path /etc/kafka/ writable] FAILED !
```
So thats what this change is for. I've reviewed all other instances of `dub path * writable` in this repo, and no other changes were required.

fix: Ownership of appuser directories.

---

ce-kafka/Dockerfile.ubi8
kafka-connect-base/Dockerfile.ubi8
kafka/Dockerfile.ubi8
server-connect-base/Dockerfile.ubi8
server/Dockerfile.ubi8
zookeeper/Dockerfile.ubi8

This restores the root groups write access to confluent service directories.
Internally (@rohit2b) and externally (@erikgb) this change works in an OpenShift context.

fix: Restore root group write access to directories

---

ce-kafka/Dockerfile.ubi8
kafka/Dockerfile.ubi8
server/Dockerfile.ubi8
zookeeper/Dockerfile.ubi8

Correct the chown and chmod order between different docker images.
Gives ug+w access on /var/log/kafka dir. (/var/log/confluent already have correct permission).
Because of missing write permission images were failing on openshift
Hi @andrewegel PR is is line with the your recent merges. This also solves log standing issue #53
Rebased with 5.4.x

fix #53 chown/chmod order and permission issue

---

zookeeper/include/etc/confluent/docker/configure
zookeeper/test/test_zookeeper.py

Fixes #92 where Zookeeper wouldn't start if you only specify `ZOOKEEPER_SECURE_CLIENT_PORT` but not `ZOOKEEPER_CLIENT_PORT`.
Unfortunately I couldn't get the test suite running by myself. Would be great if someone could do this before merging.

fix: Require either ZOOKEEPER_CLIENT_PORT or ZOOKEEPER_SECURE_CLIENT_PORT

---

server-connect-base/Dockerfile.ubi8

While reviewing container hierarchy for the ongoing SBOM work I have noticed that cp-server-connect-base image that is based on cp-server has a redundant commands for installing confluent-security package.
Package installed here in cp-server:
https://github.com/confluentinc/kafka-images/blob/5.5.x/server/Dockerfile.ubi8#L74
cp-server-connect-base is based on cp-server:
https://github.com/confluentinc/kafka-images/blob/5.5.x/server-connect-base/Dockerfile.ubi8#L20
This change should have no functional effect and it's purely cosmetic cleanup.
duplicate of https://github.com/confluentinc/kafka-images/pull/198 this time merging to 5.5.x instead of master

remove unnecessary package install command

---

kafka-connect-base/include/etc/confluent/docker/kafka-connect.properties.template

Context: https://confluent.slack.com/archives/C04F9R1AP2R/p1674810230472559
Kafka connect fails to start up when telemetry reporter is set, kafka-connect does not need telemetry reporter so exclude `CONNECT_METRIC_REPORTERS` from the list of properties during property generation.

Exclude telemetry reporter during kafka-connect property generation

---

local/pom.xml

The `confluent-local` [PR](https://github.com/confluentinc/kafka-images/pull/211) was merged in the branch `7.4.x`
We did [pint merge](https://jenkins.confluent.io/job/tools-autotasks/job/tools-autotasks/job/apply-pint-merge/2556/console) to the master.
This PR updates the version in the `pom.xml` of the `local` module after the pint merge

Bump up the version of confluent-local pom

---

examples/confluent-server-oauth/README.md
examples/confluent-server-oauth/create-certificates.sh
examples/confluent-server-oauth/docker-compose.yml
examples/confluent-server-oauth/keycloak-realm-export.json

Adds docker examples for OAuth support in Confluent server.
From CP 7.6 release onwards, it’s possible to create a minimal CP setup (consisting only of the broker and MDS) operating seamlessly without LDAP. Client applications can effortlessly produce and consume data through Kafka, with RBAC authorization managed via MDS.
This is achieved through [client-credentials](https://auth0.com/docs/get-started/authentication-and-authorization-flow/client-credentials-flow) support in Kafka, ensuring that Kafka clients can produce and consume data without any reliance on LDAP. Tokens now serve as the source of groups, eliminating the previous reliance on LDAP. This simplification supports group authorization when using RBAC.
However, LDAP can also be used with OAuth (for migrations) which is not …

CPSEC-46: Adds docker examples for OAuth in Confluent Server

---

.semaphore/cp_dockerfile_build.yml
.semaphore/semaphore.yml
service.yml

The `maven-phase` from 6.2 to 7.3 are `package` while it's `verify` in the versions later than 7.4.
This pr reverts the two commits that change `verify` to `package`.

Revert two semaphore changes from versions after 7.4.x

---

service.yml

arm64 docker builds are enabled from 7.0.x version onwards.

[MINOR] Disable build_arm in 6.2.x

---

service.yml

confluent-local is only introduced from 7.4.x. This patch adds confluent-local to docker repos.

add confluent-local to service.yml

---

kafka/include/etc/confluent/docker/kafka.properties.template
server/include/etc/confluent/docker/kafka.properties.template

With recent changes done to remove zookeeper from kafka-images, `other_props` was variable definition was deleted from template file [here](https://github.com/confluentinc/kafka-images/commit/dbae484c01c4c7b262325bfd263e7f0859e2dd59#diff-50266ac00cfedb6b06dd955cedffd417603555c2e9da4241147c600c51d8387eL15). But not all usage of that variable were removed. 
This is leading to build failure for ksql-images [here](https://semaphore.ci.confluent.io/workflows/f49cb800-c2b4-400a-a6be-a13c01f7552f?pipeline_id=1508c16e-9ef8-48f7-9a09-d5ea22d16e63) as cp-server is used for testing.

remove undefined variable in template

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml

This PR updates the Ubuntu version from 20.04 to 24.04 in the .semaphore directory files.

Update Ubuntu version from 20.04 to 24.04 in FedRAMP Branch

---

.semaphore/cp_dockerfile_build.yml
.semaphore/cp_dockerfile_promote.yml
.semaphore/semaphore.yml

This PR updates the Ubuntu version from 20.04 to 24.04 in the .semaphore directory files.

Update Ubuntu version from 20.04 to 24.04 in FedRAMP RC branch

---

.semaphore/cp_dockerfile_promote.yml

- As a first step, we plan to ship the cp-server-native image with the CP 8.0.1 release. We’ll gather feedback from this release before deciding whether to include it in all future major and minor CP releases.
- Accordingly, updated .semaphore/cp_dockerfile_promote.yml to add blocks for promoting the cp-server-native Docker image on DockerHub. For now, this change is only required in the 8.0.x branch.

Update promotion pipeline to include cp-server-native for 8.0.x

---

kafka/include/etc/confluent/docker/log4j2.yaml.template
server/include/etc/confluent/docker/log4j2.yaml.template

This PR introduces an override option for log4j configuration via environment variables. Currently, when additional settings are passed through the KAFKA_LOG4J_LOGGER environment variable, they are appended to the default configuration instead of replacing it. This change ensures that the provided configuration can properly override the defaults.
Testing: This fix has been tested locally, all existing environment variables work identically with no behavioral changes. Logger deduplication, property generation, and YAML formatting produce valid configurations.
The PR build is failing due to incorrect parsing of rpm url. This is not related to PR changes. Successful PR build for same changes in 8.1.x: https://github.com/confluentinc/kafka-images/pull/434

Resolve log4j config issue with env variable overrides
